server:
  port: 8081
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
    session:
      timeout: 60m

spring:
  datasource:
    url: ${data.url}
    username: ${data.username}
    password: ${data.password}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      # ?? ??? ??, ?????? ?? ? ?????? ???? ??
      ddl-auto: create-drop
      # ?? ??????? ??? ?? none ?? validate? ???? Hibernate? ???? ???? ??? ?.
      # ddl-auto: none
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDB106Dialect

  debug: true