server:
  port: 8081
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
    session:
      timeout: 60m

spring:
  datasource:
    url: jdbc:mariadb://infodb.ansan.ac.kr:3306/db2451506_db_practice
    username: i2451506
    password: qkr#wkd#ghks
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      # ?? ??? ??, ?????? ?? ? ?????? ???? ??
      ddl-auto: create-drop
      # ?? ??????? ??? ?? none ?? validate? ???? Hibernate? ???? ???? ??? ?.
      # ddl-auto: none
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDB106Dialect

  debug: true